backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/img"
collections:
  - label: "Business Context notes"
    name: "Business Context notes"
    folder: "Website/docs/digitalsupportnotes/Business Context"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Communications in the sector notes"
    name: "Communications in the sector notes"
    folder: "Website/docs/digitalsupportnotes/Communication in the sector"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Data notes"
    name: "Data notes"
    folder: "Website/docs/digitalsupportnotes/Data"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Data Analysis notes"
    name: "Data analysis notes"
    folder: "Website/docs/digitalsupportnotes/Data Analysis"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Digital Environments notes"
    name: "Digital Environments notes"
    folder: "Website/docs/digitalsupportnotes/Digital Environments"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Diversity and Inclusion notes"
    name: "Diversity and Inclusion notes"
    folder: "Website/docs/digitalsupportnotes/Diversity and Inclusion"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}