backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/img"
collections:
  - label: "Notes"
    name: "notes"
    folder: "docs"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}